### ISSUE TITLE
Cost for probablyGood cycleway should be lower than for unknown cycleway

### ISSUE THREAD

**Issue by xuiqzy** [FFMbyBicycle/brouter-cycling-profiles#3]
https://github.com/FFMbyBicycle/brouter-cycling-profiles/blob/912a53f9aeb5611c66cfd5b0977fd01f1ce8e298/FFMbyBicycle-long-distance-cycling.brf#L283

The cost (?) for a `probablyGood` cycleway seems to be higher (1.1) than if nothing special is known about the cycleway (1.0). I don't understand much about the routing profile format, but looking at other similar if else cases, this seems to be in the wrong order here.

**Comment by FFMbyBicycle** [comment]
Thanks for the report, you're absolutely right! I will fix this in a few minutes. Due to the low cost difference it shouldn't have a large impact, but of course it should be the other way around.
