### ISSUE TITLE
Missing surfaces

### ISSUE THREAD

**Issue by Nakaner** [FFMbyBicycle/brouter-cycling-profiles#4]
I was just having a look at your profile and comparing it with my personal preference and local knowlede of my "optimised" routes. While doing so, I found out that your profile misses a couple of surfaces:

* `concrete:lanes` is better than ground/grass but worse than concrete because there can be small steps between the plates (depends on age and region).
* `concrete:plates` is used for pre-fabricated concrete plates (but I expect some mappers to use it for in-situ concrete as well. True concrete plates roads are horrible, especially in former GDR (having lived there for a couple of years).
* `metal`: worse than asphalt, better than concrete plates, common on bridges for pedestrians and cyclists
* `grass_paver`: horrible to ride, unusual as surface except parking slots and short sections on agricultural tracks

You might compare your profile with https://taginfo.openstreetmap.org/keys/surface#values and https://taginfo.geofabrik.de/europe/germany/keys/surface#values

**Comment by FFMbyBicycle** [comment]
Thanks, I added metal (ispaved) and grass_paver (is_unpaved). However concrete:lanes and concrete:plates are currently not supported by Brouters lookup table. I opened an issue for this: https://github.com/abrensch/brouter/issues/404

**Comment by FFMbyBicycle** [comment]
I now added a basic handling of concrete:lanes concrete:plates, see https://github.com/abrensch/brouter/issues/61#issuecomment-331719109 for details.

Maybe I will add a feature in the future to set more complex costs for each surface, at the moment there are only 2 categories (paved/unpaved). I think the request is resolved :-)
